#@ load("@ytt:data", "data")

---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: svelete-app2
  namespace: develop
  labels:
    app.kubernetes.io/part-of: svelete-app
    apps.tanzu.vmware.com/workload-type: web
spec:
  serviceClaims: bindings-place-holder
  source:
    git:
      url: https://github.com/tsfrt/svelteKit-test
      ref:
        branch: main
  build:
    env:
      - name: NODE_OPTIONS
        value: ""